EXECROOT = "/cluster/home02/infk/pejulia/bin"
DATAROOT = "/cluster/home02/infk/pejulia/project/tandem_repeat/TRD_helper_data"
DATAROOT2 = "/My/Dataroot/brutus_scratch"
RESULTROOT = "/Save/my/results/here"
ROOT = "/Root/of/my/filesystem"
